### ISSUE TITLE
Links for two talks I attended

### ISSUE THREAD

**Issue by xob** [pelletiermaxime/confoo-mtl-2018-decks#1]
Building Cross Platform Progressive Web Apps, by Simon MacDonald:
Web: https://www.simonmacdonald.com/
Twitter: https://twitter.com/macdonst
Slides: http://slides.com/simonmacdonald/cross-platform-pwa-19-23-28#/

MJML, le nouveau standard pour écrire nos emails, by Thomas Deneulin:
Web: https://essential-dev-skills.com/
Twitter: https://twitter.com/TDeneulin
Slides: https://essential-dev-skills.com/MJML

**Comment by pelletiermaxime** [comment]
I would appreciate a PR. If you can't for some reason, I will try to add those links tonight or tomorrow. Thanks!
